categories:
  - name: "General"
    description: "Have any question? Ask here! :)"
    emoji: 💬
    is_announcement_only: false

  - name: "Announcements"
    description: "Official updates and news from the maintainers."
    emoji: 📢
    is_announcement_only: true
